# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab3ffd112b4e09f3b6297af331084a1a782b8a651c1a487a2c9db5b35ef96f7a750df8de19afb817569fc7f07ac4495c759bcb744b1f322a1c57d64cc38f736f

test:
  secret_key_base: 6e4078a47eb9abe7805614cd7b25f204f242720c1f6c82dea38521d49560d584ecfe924480599924b18fd745c4d381ebd00c4d28b5b239ddea7b1950287eb5d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
